import os
import numpy as np
from typing import Dict, Any
from dataclasses import dataclass

from autoquantum.visualization.plot import PESPlotter, DynamicsPlotter, WavePacketPlotter


class DashboardGenerator:
    def __init__(self, results: Dict[str, Any], config):
        self.results = results
        self.config = config
        self.output_dir = config.output_dir

    def generate_all(self):
        os.makedirs(self.output_dir, exist_ok=True)

        self._plot_pes()
        self._plot_nn_fit()
        self._plot_dynamics()
        self._generate_html_report()

    def _plot_pes(self):
        grid = self.results.get("pes_grid")
        values = self.results.get("pes_values")
        if grid is not None and values is not None:
            PESPlotter.plot_pes(
                grid, values,
                save_path=os.path.join(self.output_dir, "pes_original.png"),
            )

    def _plot_nn_fit(self):
        grid = self.results.get("pes_grid")
        values = self.results.get("pes_values")
        fitted = self.results.get("nn_fitted_values")
        if all(x is not None for x in [grid, values, fitted]):
            PESPlotter.plot_pes(
                grid, values, fitted,
                save_path=os.path.join(self.output_dir, "pes_nn_fit.png"),
            )

    def _plot_dynamics(self):
        result = self.results.get("dynamics_result")
        if result is not None:
            DynamicsPlotter.plot_transmission(
                result.energy, result.transmission, result.reflection,
                save_path=os.path.join(self.output_dir, "transmission.png"),
            )

    def _generate_html_report(self):
        html_path = os.path.join(self.output_dir, "report.html")
        result = self.results.get("dynamics_result")

        lines = [
            "<!DOCTYPE html><html><head>",
            "<title>AutoQuantum Report</title>",
            "<style>body{font-family:Arial,sans-serif;margin:40px;background:#f5f5f5}",
            ".container{max-width:900px;margin:0 auto;background:white;padding:30px;border-radius:8px;box-shadow:0 2px 10px rgba(0,0,0,0.1)}",
            "h1{color:#2c3e50;border-bottom:3px solid #3498db;padding-bottom:10px}",
            "h2{color:#2980b9;margin-top:30px}",
            ".stat{display:inline-block;background:#ecf0f1;padding:10px 20px;margin:5px;border-radius:5px}",
            ".stat-value{font-size:1.4em;font-weight:bold;color:#2c3e50}",
            ".stat-label{font-size:0.85em;color:#7f8c8d}",
            "img{max-width:100%;margin:15px 0;border:1px solid #ddd;border-radius:4px}",
            "footer{text-align:center;color:#95a5a6;margin-top:40px;font-size:0.85em}",
            "</style></head><body>",
            "<div class='container'>",
            f"<h1>AutoQuantum: {self.config.system_name}</h1>",
            "<h2>System Parameters</h2>",
            f"<div class='stat'><div class='stat-value'>{self.config.mass}</div><div class='stat-label'>Mass (au)</div></div>",
            f"<div class='stat'><div class='stat-value'>{self.config.pes_type}</div><div class='stat-label'>PES Type</div></div>",
            f"<div class='stat'><div class='stat-value'>{self.config.n_pes_points}</div><div class='stat-label'>PES Points</div></div>",
        ]

        if result is not None:
            lines.extend([
                "<h2>Dynamics Results</h2>",
                f"<div class='stat'><div class='stat-value'>{result.energy[0]:.4f} - {result.energy[-1]:.4f}</div><div class='stat-label'>Energy Range (au)</div></div>",
                f"<div class='stat'><div class='stat-value'>{result.transmission.max():.3f}</div><div class='stat-label'>Max Transmission</div></div>",
                f"<div class='stat'><div class='stat-value'>{result.reflection.min():.3f}</div><div class='stat-label'>Min Reflection</div></div>",
            ])

        img_dir = self.output_dir
        imgs = ["pes_original.png", "pes_nn_fit.png", "transmission.png"]
        for img in imgs:
            path = os.path.join(img_dir, img)
            if os.path.exists(path):
                lines.append(f"<h2>{img.replace('.png','').replace('_',' ').title()}</h2>")
                lines.append(f"<img src='{img}' alt='{img}'>")

        lines.extend([
            "<footer>Generated by AutoQuantum v0.1.0</footer>",
            "</div></body></html>",
        ])

        with open(html_path, "w") as f:
            f.write("\n".join(lines))
        print(f"  Saved: {html_path}")
